(()=>{
const $=s=>document.querySelector(s);const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const parse=s=>new Date(s+'T12:00:00');const gap=(a,b)=>Math.round((parse(b)-parse(a))/86400000);const signed=()=>{try{return!!JSON.parse(localStorage.getItem('lifelingo_user')||'null')}catch{return false}};const uid=()=>{try{return(JSON.parse(localStorage.getItem('lifelingo_user')||'null')?.email||'guest').toLowerCase()}catch{return'guest'}};const sKey=()=>`lifelingo_clean_study_${uid()}`,rKey=()=>`lifelingo_clean_retention_${uid()}`;
function load(k,f){try{return Object.assign(f,JSON.parse(localStorage.getItem(k)||'{}'))}catch{return f}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function study(){const s=load(sKey(),{dates:[],dailyDone:{}});s.dates=[...new Set(s.dates||[])].sort();s.dailyDone=s.dailyDone||{};return s}function retention(){const r=load(rKey(),{seconds:{},sessions:0});r.seconds=r.seconds||{};return r}
function streak(ds){if(!ds.length)return 0;const today=dayKey(),last=ds.at(-1);if(gap(last,today)>1)return 0;let n=1;for(let i=ds.length-1;i>0;i--){if(gap(ds[i-1],ds[i])===1)n++;else break}return n}
function fmt(sec){sec=Math.round(sec||0);if(sec<60)return `${sec}s`;const m=Math.round(sec/60);if(m<60)return `${m}m`;const h=Math.floor(m/60),r=m%60;return r?`${h}h ${r}m`:`${h}h`}
function last7(){const a=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-i);a.push({key:dayKey(d),label:d.toLocaleDateString('en',{weekday:'short'}).slice(0,2)})}return a}
function phrase(day){return (window.LIFELINGO_365||[])[Math.max(0,Math.min(364,day-1))]||"How's it going?"}
const ctx={
"How's it going?":['You see a friend you have not met for a few days. Greet them and ask how they are.','اوضاع چطوره؟'],
"I'm just looking.":['A shop assistant asks: “Can I help you?” You do not need help yet.','فقط دارم نگاه می‌کنم.'],
"That works for me.":['Someone suggests meeting at 3 PM. Accept the time naturally.','برای من مناسبه.'],
"Sounds good to me.":['A friend suggests a plan you like. Agree casually.','به نظرم خوبه.'],
"No worries.":['Someone apologizes for a small mistake. Reassure them.','اشکالی نداره.'],
"Take your time.":['Someone is rushing because they think you are waiting. Tell them not to hurry.','عجله نکن.'],
"Could you say that again?":['You did not hear what someone said. Ask them to repeat it politely.','میشه دوباره بگید؟'],
"Could you speak more slowly?":['Someone is speaking too fast for you to follow. Ask politely.','میشه کمی آهسته‌تر صحبت کنید؟'],
"I'm on my way.":['A friend texts “Where are you?” You have already left and are heading there.','توی راهم.'],
"I'm running late.":['You will arrive later than planned. Let the other person know.','دارم دیر می‌رسم.']};
function info(p){return ctx[p]||['Use the phrase naturally in this situation. Imagine someone is waiting for your answer.','اگر گیر کردی، معنی جمله را به فارسی چک کن و دوباره خودت انگلیسی بگو.']}
function currentDaily(s){const today=dayKey(),hasToday=s.dates.includes(today);return Math.min(365,Math.max(1,s.dates.length+(hasToday?0:1)))}
function ensureGuest(){const home=$('#home'),hero=home?.querySelector('.hero');if(!hero||$('#ll41Guest'))return;const el=document.createElement('section');el.id='ll41Guest';el.className='ll41Guest';el.innerHTML=`<div class="ll41Eyebrow">TRY BEFORE YOU SIGN UP</div><h3>Could you handle passport control in English?</h3><p>One real situation. Speak your way through it, then save your progress when you are ready.</p><div class="ll41Actions"><button class="primary" data-try-passport>Try Passport Control</button><button data-open-login>Log in</button></div>`;hero.after(el)}
function openGuestPassport(){try{if(typeof window.openPath==='function'&&typeof window.startMission==='function'){window.openPath('migration');setTimeout(()=>window.startMission(0),60);return}}catch{}document.querySelector('[data-path="migration"]')?.click();setTimeout(()=>document.querySelector('.mission:not(.locked)')?.click(),120)}
function hostAfter(anchor,id){let h=$('#'+id);if(!h){h=document.createElement('div');h.id=id;anchor?.after(h)}return h}
function renderDaily(){const s=study(),today=dayKey(),day=currentDaily(s),st=streak(s.dates),p=phrase(day),[scenario,fa]=info(p),pct=day/365*100,done=!!s.dailyDone[today];const targets=[];const hp=$('#home .paths');if(hp)targets.push(hostAfter(hp,'ll41DailyHome'));const ph=$('#profile .hub');if(ph)targets.push(hostAfter(ph,'ll41DailyProfile'));for(const h of targets){if(!h)continue;h.innerHTML=`<section class="ll41Daily ${done?'isDone':''}" data-daily-day="${day}"><div class="ll41Top"><div><div class="ll41Eyebrow">DAILY MINI LESSON</div><h3>Day ${day} <small>of 365</small></h3></div><div class="ll41DailyState">${done?'✓ Done today':`🔥 ${st} streak`}</div></div><div class="ll41Road"><i style="width:${pct}%"></i></div><div class="ll41Meta"><span>${pct.toFixed(1)}% roadmap</span><span>${s.dates.length} study day${s.dates.length===1?'':'s'}</span></div><div class="ll41Phrase"><div class="ll41LearnHead"><div><div class="ll41Eyebrow">LEARN</div><div class="ll41PhraseText">${p}</div></div><button class="ll41Listen" data-listen aria-label="Listen">🔊</button></div><div class="ll41Scenario">${scenario}</div>${done?`<div class="ll41DoneBox"><b>✓ Daily complete</b><span>You got it right. Come back tomorrow for the next phrase.</span><button data-daily-replay>Practice again</button></div>`:`<div class="ll41Challenge"><div class="ll41ChallengeHead"><b>Now answer from memory</b><span>Speak or type what you would say.</span></div><div class="ll41Practice"><button data-daily-mic aria-label="Speak">🎙️</button><input data-daily-input autocomplete="off" autocapitalize="sentences" placeholder="Your answer…"><button class="ll41Check" data-daily-check>Check</button></div><div class="ll41Feedback" data-daily-feedback></div><div class="ll41AnswerRow"><button data-answer>Show answer</button><button data-fa>Persian help</button></div><div class="ll41HelpBox" data-helpbox></div></div>`}</div></section>`}}
function norm(s){return String(s||'').toLowerCase().replace(/[’‘]/g,"'").replace(/\bi'm\b/g,'i am').replace(/\bi’ve\b/g,'i have').replace(/\bi'd\b/g,'i would').replace(/\bi'll\b/g,'i will').replace(/\bdon't\b/g,'do not').replace(/\bdidn't\b/g,'did not').replace(/\bcan't\b/g,'cannot').replace(/\bcouldn't\b/g,'could not').replace(/\bwon't\b/g,'will not').replace(/\bit's\b/g,'it is').replace(/\bthat's\b/g,'that is').replace(/\bwhat's\b/g,'what is').replace(/\s+/g,' ').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function similarity(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b||a.includes(b))return 1;const A=a.split(' '),B=b.split(' '),setA=new Set(A);let hit=0;B.forEach(x=>setA.has(x)&&hit++);const coverage=hit/Math.max(1,B.length),extra=Math.max(0,A.length-B.length),penalty=Math.min(.12,extra*.02);return Math.max(0,coverage-penalty)}
function completeDaily(card){const s=study(),d=dayKey();s.dailyDone[d]=true;if(!s.dates.includes(d)){s.dates.push(d);s.dates.sort()}save(sKey(),s);card.classList.add('justCompleted');setTimeout(()=>renderDaily(),650);renderRetention()}
function checkDaily(root){const card=root.closest('.ll41Daily'),inp=root.querySelector('[data-daily-input]'),fb=root.querySelector('[data-daily-feedback]'),p=card.querySelector('.ll41PhraseText').textContent.trim(),v=inp.value.trim(),sc=similarity(v,p);fb.className='ll41Feedback '+(sc>=.86?'good':sc>=.62?'mid':'bad');if(!v){fb.textContent='Say or type your answer first.';return}if(sc>=.86){fb.textContent='✓ Exactly — that sounds right.';completeDaily(card)}else if(sc>=.62)fb.textContent='Almost. Your meaning is close — try once more.';else fb.textContent='Not quite yet. Try again or show the answer.'}
let lastTick=Date.now(),session=false,gameWas=false,completeWas=false;function tick(){const now=Date.now();document.body.classList.toggle('ll41Signed',signed());if(signed()&&!document.hidden){const r=retention(),d=dayKey(),delta=Math.min(12,Math.max(0,(now-lastTick)/1000));r.seconds[d]=(r.seconds[d]||0)+delta;if(!session){r.sessions++;session=true}save(rKey(),r)}lastTick=now;const game=$('#game'),on=!!(game?.classList.contains('show')&&game.getClientRects().length);if(on&&!gameWas&&signed()){const s=study(),d=dayKey();if(!s.dates.includes(d)){s.dates.push(d);s.dates.sort();save(sKey(),s);renderDaily()}}gameWas=on;const comp=$('#complete'),done=!!(comp?.classList.contains('show')&&on);if(done&&!completeWas)ensureShare(comp);completeWas=done}
function renderRetention(){const p=$('#profile');if(!p||!signed())return;let h=$('#ll41Retention');if(!h){h=document.createElement('section');h.id='ll41Retention';h.className='ll41Retention';(p.querySelector('#ll41DailyProfile')||p.querySelector('.hub'))?.after(h)}const s=study(),r=retention(),week=last7(),weekSec=week.reduce((n,x)=>n+(r.seconds[x.key]||0),0),max=Math.max(60,...week.map(x=>r.seconds[x.key]||0)),present=Object.keys(r.seconds).filter(k=>(r.seconds[k]||0)>=30).length,activeWeek=week.filter(x=>(r.seconds[x.key]||0)>=60).length,st=streak(s.dates),weekMin=Math.round(weekSec/60);h.innerHTML=`<div class="ll41Top"><div><div class="ll41Eyebrow">YOUR LIFELINGO LIFE</div><h3>${present} days lived in English</h3></div><div class="ll41Streak">🔥 ${st} day streak</div></div><div class="ll41Stats"><div class="ll41Stat"><b>${present}</b><small>Days present</small></div><div class="ll41Stat"><b>${s.dates.length}</b><small>Study days</small></div><div class="ll41Stat"><b>${fmt(r.seconds[dayKey()]||0)}</b><small>Today</small></div><div class="ll41Stat"><b>${fmt(weekSec)}</b><small>This week</small></div></div><div class="ll41Bars">${week.map(x=>`<div class="ll41Day"><div class="ll41BarWrap"><i class="ll41Bar" title="${fmt(r.seconds[x.key]||0)}" style="height:${Math.max(3,Math.round((r.seconds[x.key]||0)/max*100))}%"></i></div><span>${x.label}</span></div>`).join('')}</div><div class="ll41Goal"><div class="ll41GoalHead"><b>Weekly presence</b><span>${activeWeek}/5 days</span></div><div class="ll41Track"><i style="width:${Math.min(100,activeWeek/5*100)}%"></i></div></div><div class="ll41Goal"><div class="ll41GoalHead"><b>Weekly practice</b><span>${weekMin}/90 min</span></div><div class="ll41Track"><i style="width:${Math.min(100,weekMin/90*100)}%"></i></div></div>`}
function ensureShare(comp){if(!comp||comp.querySelector('.ll41Share'))return;const box=document.createElement('div');box.className='ll41Share';box.innerHTML='<button data-share-result>Share result</button><button data-challenge>Challenge a friend</button>';comp.appendChild(box)}async function share(challenge){const title=$('#missionTitle')?.textContent?.trim()||'LifeLingo mission',text=challenge?`Can you beat my LifeLingo score in ${title}?`:`I just finished ${title} in LifeLingo.`;const url=new URL(location.href);url.search='';url.searchParams.set('challenge','1');url.searchParams.set('mission',title);try{if(navigator.share)await navigator.share({title:'LifeLingo',text,url:url.toString()});else await navigator.clipboard.writeText(`${text} ${url}`)}catch{}}
function speakPhrase(card){const p=card?.querySelector('.ll41PhraseText')?.textContent||'';if(window.speak)window.speak(p);else if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(p);u.lang='en-US';speechSynthesis.speak(u)}}
function refresh(){ensureGuest();renderDaily();renderRetention();document.body.classList.toggle('ll41Signed',signed())}
document.addEventListener('click',e=>{const t=e.target;if(t.closest('[data-try-passport]'))openGuestPassport();if(t.closest('[data-open-login]'))$('#loginBtn')?.click();const practice=t.closest('.ll41Practice');if(t.closest('[data-daily-check]')&&practice)checkDaily(practice);if(t.closest('[data-listen]'))speakPhrase(t.closest('.ll41Daily'));if(t.closest('[data-answer]')){const card=t.closest('.ll41Daily'),h=card?.querySelector('[data-helpbox]'),p=card?.querySelector('.ll41PhraseText')?.textContent||'';if(h){h.innerHTML=`<b>Answer</b><span>${p}</span><button type="button" data-listen>🔊 Listen</button>`;h.classList.add('show')}}if(t.closest('[data-fa]')){const card=t.closest('.ll41Daily'),p=card?.querySelector('.ll41PhraseText')?.textContent||'',h=card?.querySelector('[data-helpbox]');if(h){h.innerHTML=`<b>Persian help</b><span dir="rtl">${info(p)[1]}</span>`;h.classList.add('show')}}if(t.closest('[data-daily-replay]')){const card=t.closest('.ll41Daily');card?.classList.remove('isDone');const s=study();s.dailyDone[dayKey()]=false;save(sKey(),s);renderDaily()}if(t.closest('[data-daily-mic]')){const card=t.closest('.ll41Daily'),inp=card?.querySelector('[data-daily-input]'),fb=card?.querySelector('[data-daily-feedback]'),SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){if(fb){fb.className='ll41Feedback mid';fb.textContent='Voice recognition is unavailable here — type instead.'}}else{const r=new SR();r.lang='en-US';r.interimResults=false;if(fb){fb.className='ll41Feedback';fb.textContent='Listening…'}r.onresult=x=>{inp.value=x.results[0][0].transcript;checkDaily(inp.closest('.ll41Practice'))};r.onerror=()=>{if(fb){fb.className='ll41Feedback mid';fb.textContent='I could not hear clearly. Try again or type it.'}};r.start()}}if(t.closest('[data-share-result]'))share(false);if(t.closest('[data-challenge]'))share(true);if(t.closest('#profileBtn,#loginBtn,#logoutBtn,.mission,[data-path],#continueBtn,#nextMission,#exit'))setTimeout(refresh,120)});
document.addEventListener('visibilitychange',()=>lastTick=Date.now());setInterval(()=>{tick();if($('#profile')?.classList.contains('show'))renderRetention()},5000);refresh();tick();
})();
