(()=>{
const $=s=>document.querySelector(s);const user=()=>{try{return JSON.parse(localStorage.getItem('lifelingo_user')||'null')}catch{return null}};const key=()=>`lifelingo_social_${String(user()?.email||'guest').toLowerCase()}`;
const avatars=[['🦁','Lion'],['🐯','Tiger'],['🐼','Panda'],['🐶','Dog'],['🐱','Cat'],['🦊','Fox'],['🐨','Koala'],['🐰','Rabbit'],['👩🏻‍🦱','Curly'],['👩🏽‍🦱','Curly'],['👩🏻','Straight'],['👩🏾','Straight'],['👱🏻‍♀️','Blonde'],['🧕🏻','Hijab'],['🧕🏽','Hijab'],['👩🏻‍🦰','Red hair'],['👨🏻‍🦱','Curly'],['👨🏽‍🦱','Curly'],['👨🏻','Classic'],['👨🏾','Classic'],['👱🏻‍♂️','Blonde'],['👨🏻‍🦰','Red hair'],['🧔🏻','Beard'],['🧔🏽','Beard']];
const load=()=>{try{return Object.assign({avatar:0,requests:{}},JSON.parse(localStorage.getItem(key())||'{}'))}catch{return{avatar:0,requests:{}}}};const save=s=>localStorage.setItem(key(),JSON.stringify(s));
const partners=[['p1','Maya','👩🏽‍🦱','Intermediate','Travel English'],['p2','Alex','👨🏻‍🦱','Intermediate','Career English'],['p3','Sam','🦊','Upper beginner','Daily speaking']];
function host(){const p=$('#profile');if(!p||!user())return null;let h=$('#ll42Social');if(!h){h=document.createElement('section');h.id='ll42Social';h.className='ll42Social';const a=$('#ll41Retention')||$('#ll41DailyProfile')||p.querySelector('.hub');a?.after(h)}return h}
function render(tab='avatar'){const h=host();if(!h)return;h.innerHTML=`<div class="ll42SocialTop"><div><div class="ll41Eyebrow">YOUR IDENTITY</div><h3>Pick your LifeLingo avatar</h3><p>One tap. No long character editor.</p></div></div><div class="ll42Tabs"><button data-tab="avatar" class="${tab==='avatar'?'active':''}">Avatars</button><button data-tab="partners" class="${tab==='partners'?'active':''}">Find partners</button></div><div data-panel></div>`;tab==='avatar'?avatarPanel(h):partnerPanel(h)}
function avatarPanel(h){const s=load(),a=avatars[s.avatar]||avatars[0];h.querySelector('[data-panel]').innerHTML=`<div class="ll42Picked"><div class="ll42PickedIcon">${a[0]}</div><div><b>${a[1]} avatar</b><span>Selected for your LifeLingo profile</span></div><button class="ll42Share" data-share>↗ Share avatar</button></div><div class="ll42AvatarGrid">${avatars.map((x,i)=>`<button class="ll42Preset ${s.avatar===i?'active':''}" data-avatar="${i}"><span>${x[0]}</span><small>${x[1]}</small>${s.avatar===i?'<i>✓</i>':''}</button>`).join('')}</div>`}
function partnerPanel(h){const s=load();h.querySelector('[data-panel]').innerHTML=`<div class="ll42Safety">🛡️ <div><strong>Practice safely</strong><span>Both people must accept before chat. No contact details. Block/report stays available.</span></div></div><div class="ll42Partners">${partners.map(x=>`<article class="ll42Partner"><span class="ll42PartnerIcon">${x[2]}</span><b>${x[1]}</b><div class="ll42Tags"><span>${x[3]}</span><span>${x[4]}</span></div><button class="ll42Btn ${s.requests[x[0]]?'':'primary'}" data-connect="${x[0]}" ${s.requests[x[0]]?'disabled':''}>${s.requests[x[0]]?'Request sent':'Request practice'}</button><button class="ll42Report" data-report="${x[0]}">Report</button></article>`).join('')}</div><div class="ll42Notice">Partner matching is preview-only until secure accounts and moderation are connected.</div>`}
async function share(){const s=load(),a=avatars[s.avatar]||avatars[0],text=`${a[0]} I picked my LifeLingo avatar! Learn real-life English with me.`;try{if(navigator.share)await navigator.share({title:'My LifeLingo avatar',text,url:location.origin+location.pathname});else{await navigator.clipboard.writeText(text+' '+location.origin+location.pathname);alert('Share text copied!')}}catch(e){}}
function click(e){const h=e.target.closest('#ll42Social');if(!h)return;const b=e.target.closest('button');if(!b)return;if(b.dataset.tab)return render(b.dataset.tab);const s=load();if(b.dataset.avatar!==undefined){s.avatar=Number(b.dataset.avatar);save(s);return avatarPanel(h)}if(b.dataset.share!==undefined)return share();if(b.dataset.connect){s.requests[b.dataset.connect]=true;save(s);return partnerPanel(h)}if(b.dataset.report)alert('Report preview: moderation will receive reports when real accounts go live.')}
document.addEventListener('click',click);setTimeout(()=>render(),700);setInterval(()=>{if(user()&&!$('#ll42Social'))render()},2500);
})();